[[index]]
== Index

Abstract Factory (Pattern), 125, 260, 293

Abstract Instance Variable, 291

Ada, 34, 250, 258

Adapter (Pattern), 13, 188, 225, 293

ADAPTOR pattern language, 188, 191

Agree on Maxims (Pattern), 20, 22, 37

Alexander, Christopher, 12

Always Have a Running Version

(Pattern), 13, 138, 143, 167,

176, 180–182

Analyze the Persistent Data (Pattern), 51, 58, 75–77, 86, 294

Appoint a Navigator (Pattern), 20, 23,

149, 176 architecture, 19, 23, 25, 89 Arranging the Furniture, 118 AST Matching, 232

Beck, Kent, 6, 24, 50, 201

Belady, Les, xi, 196

Bennett, Simon, 64

Big Ball of Mud, 179, 243 Binder, Robert, 135, 289 black box testing, 145, 158 Blaha, Michael, 85

Boehm, Barry, 8 Brant, John, 118

Bridge to the New Town, 184

Brodie, Michael, 186 Brooks, Frederick, 105, 179 bug reports, 39 Build Confidence (Pattern), 20, 27, 31,

166, 167, 169, 171–173, 175,
181, 182, 186 business model, 22

C++, 34, 50, 118, 191, 209, 225, 250, 257,

261, 274, 284

Chapin, John, 57

Chat with the Maintainers (Pattern), 36,

38, 47, 51, 58, 61, 66, 71, 130
Chicken Little, 174, 175 Chikofsky, Elliot, 8, 11 class abuse, 11

COBOL, 209

Cobol, 118 Cockburn, Alistair, 93 code reviews, 46 code smells, 6, 45 CodeCrawler, 94, 104 coding idioms, 46 Compare Code Mechanically (Pattern),

203, 204, 238

Conserve Familiarity (Pattern), 167,

170, 196, 197

Continuous Integration, 181

Conway’s law, 42

Conway, Melvin, 42

Cook, Stephen, 44

Coplien, James, 171 Cross, James, 8, 11

Daimler-Benz, xii, xv DALI, 95 data bridge, 184 data container, 217, 219 database, 77 schema, 77

DATRIX, 209

Davis, Alan, 142, 183, 199 De Marco, Tom, 42, 103 debugger, 120 DeLano, David, 289

Deprecate Obsolete Interfaces (Pattern),

[cols="",]
|
|308
|

167, 188, 191–193, 223, 242 Deprecation, 193, 195

DESEL project, 44 design drift, xii Design Patterns, xiii, 289

DESIRE, 95

Detailed Model Capture (Pattern cluster), 14, 76, 95, 104–107

Detecting Duplicated Code (Pattern cluster), 16, 202, 203

Distinguish Public from Published Interface (Pattern), 167, 189,

190, 192

Do a Mock Installation (Pattern), 40, 44,

51, 62, 67, 69, 72

Do it, then do it right, then do it fast,

199

Do the simplest thing that will work, 31 documentation, 52 insufficient, 10 obsolete, 4

dotplot, 213 Dup, 215 duplicated code, 6, 10, 204 duplicated functionality, 10 Duploc, 215

Eiffel, 112

Eliminate Navigation Code (Pattern),

220, 222, 230, 234, 236, 238,

291, 293 Encapsulate Field (Pattern), 229, 291 encapsulation

violation of, 11, 230
Engage Customers, 169

Envy, 71

ESPRIT, xii, xv EuroPLoP, xv evolutionary prototype, 177 exploratory prototype, 177 Extract Method (Pattern), 116, 118, 203, 215, 222, 268, 271, 291

Extreme Programming, 31, 143, 173, 183

Facade (Pattern), 13, 234, 241, 293

Factor out State (Pattern), 246, 247, 256, 266, 272, 295

Factor out Strategy (Pattern), 246, 247,

256, 270, 272, 273, 295
Factory Method (Pattern), 125, 293 FAMOOS, xii, xiii, xv, 34, 50, 57, 58, 65,

71, 104, 118, 215

First Contact (Pattern cluster), 14, 36,

73, 74, 77, 96, 105

Fix Problems, Not Symptoms (Pattern),

20, 23, 26–28

Flyweight (Pattern), 92, 294 Foote, Brian, 179, 243 forces, _see_ pattern, forces foreign key, 81 forward engineering definition, 8 Fowler, Martin, 11, 24, 201, 274, 289 frameworks, xii FZI, xii, xv

God Class, 217, 219, 239

Goldberg, Adele, 22, 65

Grow Your Test Base Incrementally

(Pattern), 136, 143, 144, 162, 176, 182, 290, 291 hook method, 125, 151

IEEE, 11

If It Ain’t Broke, Don’t Fix It (Pattern),

20, 28, 30 inheritance

missing, 11 misuse of, 11
Initial Understanding (Pattern cluster), 14, 37, 76, 105, 123, 127

Interview During Demo (Pattern), 36,

40, 44, 47, 51, 54, 58, 59, 61,

66, 69, 71, 72, 87, 89, 122, 130
Introduce Null Object (Pattern), 246, 247, 265, 274, 294

Involve the Users (Pattern), 20, 27, 31,

37, 166, 167, 169, 171, 173, 197
Jackson, Daniel, 57

Java, 6, 125, 190, 193, 226, 232, 236, 250, 258, 274 Javadoc, 49

JUnit, 142, 148, 149

Keep It Simple (Pattern), 21, 31, 205

Keep the Data — Toss the Code, 184 Keller, Wolfgang, 186

Konigsberg, Allen, 49

Law of Conservation of Familiarity, 197

Law of Demeter, 218, 219, 230, 238 Law of Increasing Complexity, 5

layering

improper, 10

Learn from the Past (Pattern), 26, 108,

126, 127 legacy software, 3 legacy systems, xii

Lehman, Manny, xi, 196 literate programming, 112 Look for the Contracts (Pattern), 82, 86,

108, 122, 123, 126, 130, 293,

294, 296 Love, Tom, 179

maintenance, 39

maintenance costs, 22

Make a Bridge to the New Town

(Pattern), 28, 167, 173, 176,

179, 184 maxims, 22 MediaGeniX, 113 meetings, 24 metrics, 96, 128 Migrate Systems Incrementally

(Pattern), 27, 138, 143, 166,

167, 170, 171, 174, 186, 197 Migrating Legacy Systems, 175

Migration Strategies (Pattern cluster),

16, 138 misplaced operations, 11 modularity

lack of, 10

Most Valuable First (Pattern), 20, 22, 23, 25, 28, 165, 169, 176

Move Behavior Close to Data (Pattern),

203, 215, 219–222, 228–230,
233, 242, 291–293, 296 Move Method (Pattern), 222, 291 mural visualization, 213

navigator, 23 Nielsen, Jakob, 64 Nokia, xii, xv Nortel, 43

Null Object (Pattern), 246, 247, 274, 294 O’Callaghan, Alan, 188

pattern forces, xiv language, xiv, 14 tradeoffs, xiv

Perl, 250, 284

Planning Game, 26, 171

Pooley, Rob, 195

Present the Right Interface (Pattern),

28, 167, 175, 176, 178,
187–189, 192, 243, 244, 293 Pressman, Roger, 56

Prototype the Target Solution (Pattern),

167, 173, 175, 177, 197
Published Interface, 190, 191 Python, 214

Quantity (Pattern), 90, 294

Read all the Code in One Hour

(Pattern), 36, 40, 44, 45, 50,

51, 54, 58, 62, 66, 71, 87, 295
Record Business Rules as Tests

(Pattern), 66, 108, 121, 138,

145, 146, 157, 159, 162

Redistribute Responsibilities (Pattern cluster), 16, 104

reengineering, 10 continuous, 7, 12 definition, 8

reengineering patterns, 12, 13

form, 14

Refactor to Understand (Pattern), 14,

106, 108, 113, 115–119, 126,
164, 199, 291, 292 refactoring, 116 definition, 11

Refactoring Browser, 50, 117, 232

Regression Test After Every Change

_(Pattern), 138, 167, 175, 176,
181–183, 241, 290

Rename Attribute (Pattern), 116, 292 Rename Method (Pattern), 116, 292 Replace Conditional with

Polymorphism (Pattern), 265,
292 restructuring definition, 11

Retest Persistent Problems (Pattern),

138, 183, 290 reverse engineering, 9 definition, 8

Rewrite Rule Editor, 232 Riel, Arthur, 85, 229, 243

Rigi, 95

Rising, Linda, 289

Roberts, Don, 118

Roberts, Donald, 289

RT-100, 43

RTTI, 257

Rubin, Kenny, 22, 65

Rugaber, Spencer, 43

Sema, xv

Sema Group, xii

Semantic Wrapper, 187, 188, 239

Setting Direction (Pattern cluster), 14,

20, 165

Singleton (Pattern), 46, 294

Skim the Documentation (Pattern), 36,

40, 44, 47, 51, 52, 58, 62, 66,

87, 88
Small Releases, 173

Smalltalk, 50, 71, 130, 161, 191, 225, 232,

251, 258, 276 Sneed, Harry, 118 software maintenance, 11 definition, 11

software reuse, 7

Speak to the Round Table (Pattern), 20,

24, 74

Speculate about Design (Pattern), 58,

66, 75, 76, 80, 82, 86, 87, 94,
129, 294 spiral development lifecycle, 8

Split Up God Class (Pattern), 28, 220,

239, 243, 293 SQL, 78, 81–83 Squeak, 113, 279, 281 stakeholder, 25, 28 State (Pattern), 246, 247, 266, 295

State Patterns (Pattern language), 266, 295

Step Through the Execution (Pattern),

108, 120, 122, 126 Stevens, Perdita, 195

Stonebraker, Michael, 186

Strategy (Pattern), 246, 247, 270, 272,

295

Study the Exceptional Entities

(Pattern), 51, 75, 76, 95, 96 SUnit, 148

Sweeping it Under the Rug, 187

Template Method (Pattern), 125, 295,

296

Test Fuzzy Features (Pattern), 138, 145,

290

Test Old Bugs (Pattern), 138, 145, 290

Test the Interface, Not the Implementation (Pattern),

108, 130, 138, 143, 145, 146,

155, 158, 176 Test-Driven development, 183 testing, 135 tests

missing, 5

Tests: Your Life Insurance

(Pattern cluster), 14, 46, 67, 86, 95,

108 The Blob, 239

The Law of Continuing Change, xi

The Law of Increasing Complexity, xi

Thomsett, Rob, 42 Throwaway Code, 179 throwaway prototype, 177 Tie Code and Questions (Pattern), 106,

109, 111, 113, 117, 119, 121,

164 tradeoffs, _see_ pattern, tradeoffs

Transform Client Type Checks

_(Pattern), 222, 246, 247, 256,

257, 260, 265, 284, 292, 293
Transform Conditionals into Registration (Pattern), 246,

247, 256, 265, 277, 283, 284
Transform Conditionals to


Polymorphism (Pattern

cluster), 16, 104, 203, 214, 215,

246


Transform Self Type Checks (Pattern),

246, 247, 249, 253, 256–258,

266
UML

class diagram, 77, 82, 95
unit tests, 46 University of Bern, xii, xv

UNIX, 250

Unix, 127

Use a Testing Framework (Pattern),

136, 146, 148

Use Profiler Before Optimizing

(Pattern), 168, 198, 199
violation of encapsulation, _see_ encapsulation, violation of

Visitor (Pattern), 225, 296

Visualize Code as Dotplots (Pattern), 203, 210, 291

white box testing, 158 White, Jim, 43

Wong, Kenny, 57

Woolf, Bobby, 276

Write Tests to Enable Evolution

_(Pattern), 136, 139, 143, 156,
165, 167, 176, 183

Write Tests to Understand (Pattern),

108, 116, 117, 119, 122, 138,

147, 162, 163

XP, _see_ Extreme Programming

Yoder, Joseph, 179, 243

Yourdon, Edward, 170
